name: close-asana-task
on:
  issues:
    types: [closed]

concurrency:
  group: asana-${{ github.event.issue.number }}

jobs:
  close-asana-task:
    runs-on: self-hosted
    steps:
      - uses: psrenergy/asana-integration@master
        with:
          action: "close"
          asana-secret: "${{ secrets.ASANA_SECRET }}"
          asana-workspace: "${{ secrets.ASANA_WORKSPACE }}"
          asana-project: "${{ secrets.ASANA_PROJECT }}"